### ISSUE TITLE
Add Info to FAQ Section

### ISSUE THREAD

**Issue by zachspiel** [zachspiel/wedding-rsvp#147]
- [x] What date should I RSVP by?
- [x] Am I allowed to bring my children?
- [x] Did Han shoot first?
- [x] Will there be an open bar?
- [x] Will there be any transportation provided?
- [x] Do the bride and groom have a preferred hotel/room block?
- [x] What type of food will be served at your wedding?
- [x] Are the bride and groom nerds?
- [x]  Are animals permitted at this wedding?
- [ ]  Will your wedding be indoors or outdoors?
- [x]  What is the theme/wedding colors?
- [x]  What is the dress code for your wedding?
- [x]  Can I bring a date?
- [x]  I thought Zach loved dark mode?
- [ ]  Am I allowed to take photos at your wedding?
- [x]  What time should I arrive?
- [x] What time will the party end?
- [x] I am staying a few days in the area. What should I do?

**Comment by surfinsonie** [comment]
plz pay me more

**Comment by zachspiel** [comment]
https://www.theknot.com/content/wedding-website-faq-page

**Comment by surfinsonie** [comment]
What date should I RSVP by?
>Please RSVP by September 26th, 2024. This ensures that our vendors will have enough time to accommodate the number of guests we have.

**Comment by surfinsonie** [comment]
Am I allowed to bring my children?
>We love your children, but due to space restrictions, we cannot accommodate guests under the age of 18 on our wedding day. The only children present will be those in the wedding party. Thank you for your understanding.

**Comment by surfinsonie** [comment]
Did Han shoot first?
>In the original version of the scene, Han shoots Greedo first. Later versions are edited so that Greedo attempts to fire at Han first. Director George Lucas altered the scene to give Solo more justification for acting in self-defense.

**Comment by surfinsonie** [comment]
Will there be an open bar?
>Yes! However, our venue only allows beer and wine. We will also have an assortment of beverages for those who do not wish to partake.

**Comment by surfinsonie** [comment]
Will there be any transportation provided?
>No transportation will be provided. There is ample parking on the preemies and you will be directed to the designated parking lot by an attendant when you arrive.  If planning on drinking, please secure a designated driver or use rideshare services to ensure everyone gets home safely.

**Comment by surfinsonie** [comment]
Do the bride and groom have a preferred hotel/room block?
>Yes! The bridal party and their family will be staying at the Crowne Plaza Resort in Chandler (One N San Marcos Pl, Chandler, AZ 85225). Please reach out to the hotel directly to make a booking, should you wish to stay at the same hotel. Please note that we will be hosting a casual farewell breakfast at this hotel the morning after the wedding on October 27th to give everyone a chance to say goodbye.

**Comment by surfinsonie** [comment]
What type of food will be served at your wedding?
>We are planning on serving Italian food with a variety of desserts and appetizers. We will do our best to accommodate everyone's dietary restrictions, but due to financial constrains, it may not be feasible.

**Comment by surfinsonie** [comment]
Are the bride and groom nerds?
>Absolutely. Keep your eyes peeled for Easter eggs throughout the wedding.

**Comment by surfinsonie** [comment]
Are animals permitted at this wedding?
>Unfortunately, the only animals permitted at our wedding will be party animals.

**Comment by surfinsonie** [comment]
Will your wedding be indoors or outdoors?
>Our wedding will be both indoors and outdoors. As famously said by Kelso, "well damn Jackie, I can't control the weather!" so please plan accordingly and dress for success. The ceremony will be held outside, and the reception will be indoors. For those visiting from out of state, please check Mesa, Arizona weather as October can be unpredictable.

**Comment by surfinsonie** [comment]
What is the theme/wedding colors?
>Our theme is loosely whimsical, fantasy, garden party vibes. Our wedding colors are a mix of greens, blues, and violets. Please wear the colors that you are comfortable in, but be aware that our bridesmaids will be dressed in dark green, groomsmen in dark grey, and the groom will be in dark navy blue. Oh, and the bride's wearing white. 😉

**Comment by surfinsonie** [comment]
What is the dress code for your wedding?
>Our dress code is formal/cocktail attire. Please [check out this cheat sheet](https://www.brides.com/story/wedding-dress-code-explained) if you need further explanation.

**Comment by surfinsonie** [comment]
Can I bring a date?
>Please check your invitation or the RSVP system in the website to see how many people were invited within your party. Unfortunately, due to financial limitations, not everyone may have been allotted a plus one.

**Comment by surfinsonie** [comment]
I thought Zach loved dark mode?
>We are a dark mode family, but we thought light mode looked best for the website. See, we can prove it -->

**Comment by surfinsonie** [comment]
What time should I arrive?
>The ceremony begins at 4, so please plan accordingly to arrive on time. We recommend at least 15 minutes early so you can sign our guest book and find a good seat.

**Comment by surfinsonie** [comment]
What time will the reception end?
>The reception ends at 10. We're all too old to be staying out any later.

**Comment by zachspiel** [comment]
Enjoy your stay in Phoenix! Some of our favorite things to do are seeing a movie at Harkins Camelview, playing a round of mini golf at Imagine 3D Mini Golf, or petting the stingrays at the Phoenix Zoo.

If you're hungry, we'd recommend DC Steakhouse, Rustler's Roost, YC's Mongolian Grill, Nando's Mexican Food, or Venezia's Pizza (recognizable from the famous pizza-on-the-roof scene from Breaking Bad). For you folks on the East Coast, make sure to try In-n-Out! Life changing! 

To finish with something sweet, head over to Jeremiah's Italian Ice, Toasted Mallow, or Bruster's Real Ice Cream. For those of you inclined to try some cactus ice cream, head over to Topo Arizona in Gilbert. It's inside the giant beaver with glowing red eyes. You can't miss it.
